fix changelog multiline output
Signed-off-by: jchrist <jchrist@cytech.gr>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -48,8 +48,13 @@ jobs:
           
           # remove empty lines, otherwise changelog plugin will lose rest of content
           CHANGELOG="$(echo "$CHANGELOG" | grep -v '^$')"
+          
+          if [[ "${CHANGELOG}" == "" ]]; then
+            echo "ERROR! Empty changelog! Aborting release!"
+            exit 1
+          fi
 
-          echo 'changelog=<<EOF' >> $GITHUB_OUTPUT
+          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
           echo "${CHANGELOG}" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
 
